services:
  political-scorecard-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: psc-frontend
    ports:
      - "4200:4200"
    networks:
      - psc-network
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=dev
    command: npm run start

networks:
  psc-network:
    driver: bridge